# Generated by Django 3.1.8 on 2022-06-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='admin',
        ),
    ]
