# Generated by Django 3.1.8 on 2022-06-08 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Author'),
        ),
    ]
